title: Around the Block
author: Chris Blocher
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  All things that make a Blocher think.

# social links
twitter_username: @cblocher
github_username:  @cblocher

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minima
